### PR TITLE
First version of Herbsjs Docs

### PR DESCRIPTION
**Pull request by italojs**
# Herbsjs Docs 🏗 🥳 

This PR is about the **pre-alpha** version of herbsjs, the idea here is not only check the code but discuss about the documentation.

The documentation is developed using the [docssaurus v2](https://v2.docusaurus.io/), the interface and content structure is based on [hanamirb](https://hanamirb.org), [babeljs](https://babeljs.io/) and [react](https://pt-br.reactjs.org/).

This documentations have some parts in English and other in portuguese because I just copy past some contents from our internal Vortx documentation and some read.me's, the first ideia here is not focus in final documentation but discuss about strutucture, content and the layout. I will translate everything like we are validating the ideas.

## First page 1️⃣ 
The idea in home page is give the idea the herbsjs is clean and elegant, there we talk a little bit about hersbjs philosophy.
There we can give some code examples like [react](https://pt-br.reactjs.org/) do but I belive we need to discuss about this.

## Documentation page 📝 

The documentation page will contain the documentation about the herbjs framework and core concepts and all libraries explanation, so there you can check the herbsjs session and a gotu session, I just wrote the Suma documentation to give an example of an lib docs and because Suma is a little lib.

The left menus list the topics and the right menu list the subtopics

## Brainstorm 🤔 

So, give your opinion about: 
- First page layout
- First page content
- Like we have many libs, what libs/example do you think we can print in the home page? (like [react](https://pt-br.reactjs.org/) do.
- Documentations structure
- Documentation color
- What do you think about what can be your first blog post?
- what more you want to talk

The fist **pre-alpha** release are deployed here https://herbsjs.github.io/website/

### CODE REVIEW

**Comment by dalssoft** [comment]
A few things:

- slogan - **"Domain first - The core that matters"**

- "Herbs experience" 

> Like we have many libs, what libs/example do you think we can print in the home page? 

I would emphasize the "Herbs experience", regardless a specific lib

- Roadmap
We should have a page to describe the roadmap planned by the main maintainers. Of course, being a open source project, features not planned on this roadmap is possible

**Comment by dalssoft** [comment]
One more thing: We should have a few sample code on the first page. Maybe a few scroll downs the page, but it should be on the first page so people can have a first impression as soon as possible.

**Comment by italojs** [comment]
we have many example possibilities, what example do you have in mind?
I believe we can start showing 3 examples from differents libs: suma, gotu and buchu

something like this:

# gotu 
Gotu Kola helps define your business entities (*)

(*) Entities: they are the first natural place we should aim to place business logic in domain-driven applications.

``` js
const { entity, field } = require('gotu')

const Feature = 
        entity('Feature', {
            name: field(String),
            hasAccess: field(Boolean)
        })

const Plan = 
    entity('Plan', {
        name: field(String),
        monthlyCost: field(Number)
    })

const User = 
    entity('User', {
        name: field(String),
        lastAccess: field(Date),
        accessCount: field(Number),
        features: field([Feature]),
        plan: field(Plan),
    })

const user = new User()
user.name = "Beth"
user.plan.monthlyCost = 10
user.features = [ 
    new Feature(),
    new Feature(),
    new Feature()
]
user.validate()
```

# Buchu

Uniform, auditable and secure use case javascript library. Influenced by Clean Architecture and Trailblazer

``` js
const { entity, field } = require('gotu')
const Item = entity('Item', {
  id: field(Number),
  description: field(String),
  isDone: field(Boolean),
  position: field(Number)
})

const { Ok, Err, usecase, step, ifElse } = require('../../../src/buchu')
const dependency = {
    ItemRepository: require('../repositories/ItemRepository').ItemRepository,
    ...
}

const addOrUpdateItem = (injection) =>

    usecase('Add or Update an Item on a to-do List', {

        // Input/Request type validation 
        request: { listId: Number, item: Item },

        // Authorization Audit  
        authorize: (user) => user.isAdmin ? Ok() : Err(),

        // Dependency Injection control
        setup: (ctx) => ctx.di = Object.assign({}, dependency, injection),
      
        // Step audit and description
        'Check if the Item is valid': step((ctx) => {
            ...
            return item.validate() // Ok or Error
        }),

        'Check if the List exists': step(async (ctx) => {
            ...
            return Ok()
        }),

        // Conditional step
        'Add or Update the Item': ifElse({

            'If the Item exists': step(async (ctx) => {
                ...
                return Ok(newItem)
            }),

            'Then: Add a new Item to the List': step(async (ctx) => {
                ...
                return ctx.ret = await itemRepo.save(item) // Ok or Error
            }),

            'Else: Update Item on the List': step(async (ctx) => {
                ...
                return ctx.ret = await itemRepo.save(item) // Ok or Error
            })
        })
    })
```
 

# Suma

Suma helps with single value validations.
Extensible, test covered and errors code only!
Suma does not validate schema or objects, just single values. For schema validation take a look at herbjs/gotu.

``` js
const { validate } = require('suma')

const value = null
const validations = { presence: true }
const result = validate(value, validations) 
/* {
    value: null,
    errors: [{ cantBeEmpty: true }]
} */
```

**Comment by italojs** [comment]
I'm using the [Live Code](https://github.com/FormidableLabs/react-live) React component to show the code examples but I'm not sure about layout, what do you think about the theme:

## Dracula
image

## DuoToneLight
image

## NightOwlLight
image

## Default 
image

**Comment by jhomarolo** [comment]
@italojs, do you have any predictions about this PR? I would like to start helping on the site, but I need this PR to finish for me to do a fork

**Comment by italojs** [comment]
I'm just waiting for your or @dalssoft  approval to merge it into the master, so, for me, the first version is OK, what do think?

**Pull request merged**
